### PR TITLE
Revert "Update fsouza/go-dockerclient to the last version."

### PR DESCRIPTION
**Pull request by benjamin-guillet**
Reverts remind101/empire#614

### CODE REVIEW

**Comment by phobologic** [comment]
Did it break something?

**Comment by benjamin-guillet** [comment]
@phobologic I'm using this branch to test with my own ECS cluster. So far I had one stall `emp run` (the very first one), I can't reproduce now, it's working everytime with a few different commands.

**Comment by ejholmes** [comment]
:+1:

**Comment by ejholmes** [comment]
We're never merged this so I'm assuming the update is ok? :)

Ok to close?

**Comment by benjamin-guillet** [comment]
Yeah we can close.

**Pull request closed without merging**
