### PR TITLE
DeploymentConfiguration to ECS Services Custom Resource

### PR DESCRIPTION
**Pull request by russellballestrini**
parse DeploymentConfiguration and pass it to the create ECS Service API call.

### CODE REVIEW

**Comment by aengelas** [comment]
I can make the additional required changes. It was my changes that caused the issue.

**Comment by russellballestrini** [comment]
https://github.com/remind101/empire/pull/1158#discussion_r483734775 thanks for calling out that I didn't revert the problem PR @aengelas - preparing a PR to do so now.

**Comment by aengelas** [comment]
I don't want to review this, since I wrote a bunch off it.

**Comment by aengelas** [comment]
Related AWS support thread about strings in cf custom resources: https://remind.slack.com/archives/CDNSXHEEL/p1598398372094500

**Review by june-remind101 — APPROVED** [review]
LGTM, maybe a test or two around handling errors

**Comment by aengelas** [comment]
@hamiltop @bitglue  Do we want to continue with this and get it deployed? Seems like betterscaling might make this unnecessary?

**Comment by hamiltop** [comment]
We've had r101-api in prod with 150% max percent and I'm not sure how much it's helped or hurt.

**Comment by bitglue** [comment]
Since betterscaling rapidly terminates capacity after api deploys, the importance of reducing that "bump" from an api deploy is lower. But it would still have some benefit: currently there's about 18 minutes where the cluster is significantly overprovisioned to accommodate the deploy. There's also significant shuffling of containers around at the end of the deploy when the excess compute instances are terminated.

The other concern though is if we'd even want to make all API deployments slower just to reduce that bump.

If we did merge this functionality, I might use it to deploy betterscaling with an at-most-1 policy, rather than at-least-1. That's a pretty minor concern though: 2 betterscalings running just thrashes the ASG a bit, sometimes.

If we adopt BANDAID we may end up needing something like this since the max deployment percentage can't go over 100% for a daemon service. But, BANDAID may work with an entirely different deployment system.

I guess my feeling is there isn't a compelling use case for this functionality, but if it's implemented and works there's not much downside to merging it.

**Comment by bitglue** [comment]
> We've had r101-api in prod with 150% max percent and I'm not sure how much it's helped or hurt.

From my casual observation it does not seem to have made much of a difference either way. I suspect the rate limiting you've been investigating and/or the termination behavior of API is (still) the limiting factor in deployment speed, so we wouldn't see any change until the numbers are reduced more.

**Comment by russellballestrini** [comment]
If I remember correctly that 150% set in stacks isn't applied, we might
have applied it outside of stacks but this would need to be merged if we
want stacks to manage and maintain this value.

**Comment by june-remind101** [comment]
@remind101/ops-engineering Safe to close this at this point I assume?

**Comment by bitglue** [comment]
yes

**Pull request closed without merging**
