### PR TITLE
Issue 844

### PR DESCRIPTION
**Pull request by mhahn**
Need to test this with a real app, but this is what you and i discussed @ejholmes, removing "Scale" and just using "Release".

### CODE REVIEW

**Comment by mhahn** [comment]
Tested that this now submits 1 update to CF.

**Comment by mhahn** [comment]
Logs look like:
```
server_1  | mhahn scaled `web` on acme-inc from 2(1X) to 1(1X)
server_1  | mhahn scaled `worker` on acme-inc from 2(1X) to 1(1X)
```

we could also put it on one line, something like
```mhahn scaled `web` from 2(1X) to 1(1X) and `worker` from 2(1X) to 1(1X) on acme-inc```

**Comment by ejholmes** [comment]
This looks great to me 👍 .

One thing that I was thinking, right now in the CloudFormation backend, [we always set the RestartKey when submitting a new release](https://github.com/remind101/empire/blob/master/scheduler/cloudformation/cloudformation.go#L249). The end goal is to have a `Restart` method on the Scheduler interface, which would be the only place where we'd ever change that value.

I don't think it's a big deal right now, it just means that even with the CloudFormation backend, a new submit will always result in all new task definitions getting created and a service restarting. Once we remove that, then submitting an identical release should result in no updates.

**Comment by mhahn** [comment]
I'm going to start on: https://github.com/remind101/empire/issues/697, I'll address the above within that

**Pull request merged**
