### PR TITLE
Support log level

### PR DESCRIPTION
**Pull request by mhahn**
Fixes: https://github.com/remind101/empire/issues/929

### CODE REVIEW

**Comment by mhahn** [comment]
It would be cool to have a standard for doing these debug messages. 

ie. i like in node that you can use: https://github.com/visionmedia/debug where each file inits a debugger with some common prefix like "http"

then all the messages are prefixed:

`http: message`

which makes it easier to see where something is coming from (ie. i usually make the prefix the filename)

**Comment by ejholmes** [comment]
> It would be cool to have a standard for doing these debug messages.

I think we should be able to do that pretty easily with [CallerFileHandler](https://github.com/inconshreveable/log15/blob/03f7e3c942fe248f8dd5f5ad5e714b57ef7e419a/doc.go#L100) middleware in log15, or something similar that uses the [stack from the Record](https://github.com/inconshreveable/log15/blob/03f7e3c942fe248f8dd5f5ad5e714b57ef7e419a/doc.go#L100).

👍

**Comment by mhahn** [comment]
Oh nice, I say we start with `CallerFileHandler` and see if we need the stack details

**Comment by mhahn** [comment]
Should we enable this for debug only?

**Comment by ejholmes** [comment]
Yeah, probably only for debug 👍

**Pull request merged**
